### ISSUE TITLE
ios 11.4 扫码之后闪退

### ISSUE THREAD

**Issue by swanghao** [apicloudcom/FNScanner#2]
ios 11.4 扫码之后闪退

var FNScanner = api.require('FNScanner');
                FNScanner.open({
                    autorotation: true
                }, function(ret, err) {
                    if (ret) {
                        alert(JSON.stringify(ret));
                    } else {
                        alert(JSON.stringify(err));
                    }
                });

**Comment by sunzhengcuan** [comment]
最新版本已修复此问题
