### ISSUE TITLE
 FNScanner 扫描二维码出现中文乱码，打开相册选择却不出现

### ISSUE THREAD

**Issue by cqliulei** [apicloudcom/FNScanner#4]
在使用FNScanner 扫描二维码出现中文乱码，打开相册选择却不出现中文乱码，有没有遇到相同问题的亲们，求大神解决~
代码：

FNScanner.openScanner({
      autorotation: true,
      saveToAlbum: true,
      saveImg:{

        path: 'fs://download/erweima.jpg',  //字符串类型；保存的文件路径；若路径不存在，则创建此路径，只支持fs://协议
        w: 200,              //（可选项）数字类型；生成图片的宽度，默认：200
        h: 200               //（可选项）数字类型；生成图片的高度，默认：200
    }
  },function(ret, err) {
      console.log(JSON.stringify(ret));
});

地址：https://community.apicloud.com/bbs/thread-127817-1-1.html

**Comment by sunzhengcuan** [comment]
可能是编码不支持，用hwScanner试试，或者ACScanner
